#数据库连接信息
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://121.36.18.182:3306/psychological_consultation?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: rpz2020^
  mvc:
    format:
      date: yyyy-MM-dd
server:
  servlet:
    encoding:
      charset: UTF-8
  port: 3738

mybatis:
  mapper-locations: classpath:/mapper/*.xml, classpath:/mapper/extend/*.xml
